/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dc_block.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(539e764d5210b9e4b9b2e04aaf302e5d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/dc_block.h>
// pydoc.h is automatically generated in the build directory
#include <dc_block_pydoc.h>

void bind_dc_block(py::module& m)
{

    using dc_block    = gr::digiham::dc_block;


    py::class_<dc_block, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<dc_block>>(m, "dc_block", D(dc_block))

        .def(py::init(&dc_block::make),
           D(dc_block,make)
        )
        



        ;




}








