/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dmr_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c4cc0869d0c04c727fd39191fa2ac3f7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/dmr_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <dmr_decoder_pydoc.h>

void bind_dmr_decoder(py::module& m)
{

    using dmr_decoder    = gr::digiham::dmr_decoder;


    py::class_<dmr_decoder, gr::block, gr::basic_block,
        std::shared_ptr<dmr_decoder>>(m, "dmr_decoder", D(dmr_decoder))

        .def(py::init(&dmr_decoder::make),
           py::arg("slot_filter") = 3,
           D(dmr_decoder,make)
        )
        
        .def("set_slot_filter",
           &dmr_decoder::set_slot_filter,
           py::arg("slot_filter"),
           D(dmr_decoder,set_slot_filter)
        )
        



        ;




}








