/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dstar_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(94b22b9af76aa77f897f7ac4dd8a23e7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/dstar_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <dstar_decoder_pydoc.h>

void bind_dstar_decoder(py::module& m)
{

    using dstar_decoder    = gr::digiham::dstar_decoder;


    py::class_<dstar_decoder, gr::block, gr::basic_block,
        std::shared_ptr<dstar_decoder>>(m, "dstar_decoder", D(dstar_decoder))

        .def(py::init(&dstar_decoder::make),
           D(dstar_decoder,make)
        )
        



        ;




}








