/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fsk_demodulator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2caf1591c8f7f2dd96789b0f73556aa5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/fsk_demodulator.h>
// pydoc.h is automatically generated in the build directory
#include <fsk_demodulator_pydoc.h>

void bind_fsk_demodulator(py::module& m)
{

    using fsk_demodulator    = gr::digiham::fsk_demodulator;


    py::class_<fsk_demodulator, gr::block, gr::basic_block,
        std::shared_ptr<fsk_demodulator>>(m, "fsk_demodulator", D(fsk_demodulator))

        .def(py::init(&fsk_demodulator::make),
           py::arg("samples_per_symbol"),
           py::arg("invert") = false,
           D(fsk_demodulator,make)
        )
        



        ;




}








