/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gfsk_demodulator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a163a559aad58f166713a662bbfeb52f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/gfsk_demodulator.h>
// pydoc.h is automatically generated in the build directory
#include <gfsk_demodulator_pydoc.h>

void bind_gfsk_demodulator(py::module& m)
{

    using gfsk_demodulator    = gr::digiham::gfsk_demodulator;


    py::class_<gfsk_demodulator, gr::block, gr::basic_block,
        std::shared_ptr<gfsk_demodulator>>(m, "gfsk_demodulator", D(gfsk_demodulator))

        .def(py::init(&gfsk_demodulator::make),
           py::arg("samples_per_symbol"),
           D(gfsk_demodulator,make)
        )
        



        ;




}








