/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nxdn_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(00e1cc9f1c6cc12a3c0a94aa20383a6d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/nxdn_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <nxdn_decoder_pydoc.h>

void bind_nxdn_decoder(py::module& m)
{

    using nxdn_decoder    = gr::digiham::nxdn_decoder;


    py::class_<nxdn_decoder, gr::block, gr::basic_block,
        std::shared_ptr<nxdn_decoder>>(m, "nxdn_decoder", D(nxdn_decoder))

        .def(py::init(&nxdn_decoder::make),
           D(nxdn_decoder,make)
        )
        



        ;




}








