/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pocsag_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0d280c66181ea8c5dca482ec59a456b5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/pocsag_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <pocsag_decoder_pydoc.h>

void bind_pocsag_decoder(py::module& m)
{

    using pocsag_decoder    = gr::digiham::pocsag_decoder;


    py::class_<pocsag_decoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pocsag_decoder>>(m, "pocsag_decoder", D(pocsag_decoder))

        .def(py::init(&pocsag_decoder::make),
           D(pocsag_decoder,make)
        )
        



        ;




}








