/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ysf_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(72bf24c5cb3087fdd01f72175928df69)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/digiham/ysf_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <ysf_decoder_pydoc.h>

void bind_ysf_decoder(py::module& m)
{

    using ysf_decoder    = gr::digiham::ysf_decoder;


    py::class_<ysf_decoder, gr::block, gr::basic_block,
        std::shared_ptr<ysf_decoder>>(m, "ysf_decoder", D(ysf_decoder))

        .def(py::init(&ysf_decoder::make),
           D(ysf_decoder,make)
        )
        



        ;




}








